---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-operator
  labels:
    app: kiali-operator
    version: ${OPERATOR_VERSION_LABEL}
subjects:
- kind: ServiceAccount
  name: kiali-operator
  namespace: ${OPERATOR_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: kiali-operator
  apiGroup: rbac.authorization.k8s.io
