apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  istio-injection: enabled
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/knative-samples/helloworld-go
            imagePullPolicy: IfNotPresent
            env:
            - name: TARGET
              value: "Go Sample v1"
