---
dependency:
  name: galaxy
platforms:
- name: default
  groups:
  - k8s
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: junit
  playbooks:
    destroy: ../default/destroy.yml
    prepare: ../default/prepare.yml
  inventory:
    group_vars:
      all:
        kiali_operator_assets_path : "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
        cr_file_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/kiali-cr.yaml"
        istio:
          control_plane_namespace: istio-system
        kiali:
          accessible_namespaces: 
          - "default"
          - "istio-system"
          operator_namespace: kiali-operator
          operator_image_name: quay.io/kiali/kiali-operator
          operator_watch_namespace: "kiali-operator"
          operator_clusterrolebindings: ""
          operator_clusterroles: ""
          operator_version: latest
          auth_strategy: openshift
          image_name: quay.io/kiali/kiali
          label_selector: kiali.io/member-of={{ istio.control_plane_namespace }}
          image_version: latest
          image_pull_policy: Always
scenario:
  name: multi-tenancy
  test_sequence:
    - prepare
    - converge
    - destroy