apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kiali
  namespace: {{ kiali_vars.deployment.namespace }}
  labels:
    app: kiali
    version: {{ kiali_vars.deployment.version_label }}
  annotations:
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  backend:
    serviceName: kiali
    servicePort: {{ kiali_vars.server.port }}
