---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-faults-vs
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: reviews-faults-dr-subset-v1
      weight: 33
    - destination:
        host: reviews
        subset: reviews-faults-dr-subset-v2
      weight: 33
    - destination:
        host: reviews
        subset: reviews-faults-dr-subset-v3
      weight: 34
    fault:
      abort:
        httpStatus: 556
        percent: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-faults-dr
spec:
  host: reviews
  subsets:
  - name: reviews-faults-dr-subset-v1
    labels:
      version: v1
  - name: reviews-faults-dr-subset-v2
    labels:
      version: v2
  - name: reviews-faults-dr-subset-v3
    labels:
      version: v3
