---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-mirroring-vs
spec:
  hosts:
    - reviews
  http:
    - route:
      - destination:
          host: reviews
          subset: reviews-mirroring-dr-v1
        weight: 100
      mirror:
        host: reviews
        subset: reviews-mirroring-dr-v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-mirroring-dr
spec:
  host: reviews
  subsets:
    - name: reviews-mirroring-dr-v1
      labels:
        version: v1
    - name: reviews-mirroring-dr-v2
      labels:
        version: v2
