- name: Install Bookinfo with or without Kiali Traffic Generator
  hosts: localhost
  tasks:

    - name: Initialize Facts
      set_fact:
        istio_bookinfo_mongodb_deployment_path: files/bookinfo-mongodb.yaml
        istio_bookinfo_mongodb_service_path: files/bookinfo-ratings-v2-mongodb.yaml
        istio_bookinfo_mysql_deployment_path: files/bookinfo-mysql.yaml
        istio_bookinfo_mysql_service_path: files/bookinfo-ratings-v2-mysql.yaml
        istio_bookinfo_deployment_path: files/bookinfo.yaml
        istio_bookinfo_gateway_path: files/bookinfo-gateway.yaml
        check_retries: "{{ check_retries | default(50) }}"

    - name: Define Bookinfo Namespace if is not defined
      set_fact:
        bookinfo_namespace: 'bookinfo'
      when: bookinfo_namespace is not defined

    - name: Define Bookinfo Version if is not defined
      set_fact:
        bookinfo_version: '1.9.0'
      when: bookinfo_version is not defined

    - name: Define Rename Label if is not defined
      set_fact:
        rename_label: ''
      when: rename_label is not defined

    - name: Delete Test Bookinfo Project
      openshift_raw:
        api_version: v1
        kind: Project
        name: "{{ item }}"
        state: absent
        verify_ssl: false
      ignore_errors: true
      with_items:
        - "{{ bookinfo_namespace }}"

    - name: Create Bookinfo Project
      openshift_raw:
        api_version: v1
        kind: Project
        name: "{{ item }}"
        state: present
        verify_ssl: false
      register: projectStatus
      until: projectStatus.changed == true
      retries: "{{ hostvars['localhost']['check_retries'] }}"
      delay: 10
      with_items:
        - "{{ bookinfo_namespace }}"

    - name: Give the scc-to-user to Bookinfo
      shell: "oc adm policy add-scc-to-user privileged -z default -n {{bookinfo_namespace}}"

    - name: Deploy Bookinfo
      shell: "cat {{item}} | LABEL={{ rename_label }} VERSION={{ bookinfo_version }} envsubst   | istioctl kube-inject -f - | oc apply -n {{bookinfo_namespace}} -f -  "
      with_items:
        - "{{ istio_bookinfo_deployment_path }}"

    - name: Deploy Bookinfo Gateway
      shell: "cat {{item}}  | oc apply -n {{bookinfo_namespace}} -f -  "
      with_items:
        - "{{ istio_bookinfo_gateway_path }}"

    - name: Deploy MongoDB
      shell: "cat {{item}} |  LABEL={{ rename_label }} VERSION={{ bookinfo_version }} envsubst   | istioctl kube-inject -f - | oc apply -n {{bookinfo_namespace}} -f -  "
      when: "mongodb is defined and mongodb == 'true'"
      with_items:
        - "{{ istio_bookinfo_mongodb_deployment_path }}"
        - "{{ istio_bookinfo_mongodb_service_path }}"

    - name: Deploy MySQL
      shell: "cat {{item}} |  LABEL={{ rename_label }} VERSION={{ bookinfo_version }} envsubst    | istioctl kube-inject -f - | oc apply -n {{bookinfo_namespace}} -f -  "
      when: "mysql is defined and mysql == 'true'"
      with_items:
        - "{{ istio_bookinfo_mysql_deployment_path }}"
        - "{{ istio_bookinfo_mysql_service_path }}"

    - name: Expose Ingress Gateway
      shell: "oc expose svc istio-ingressgateway -n istio-system"
      ignore_errors: true

    - name: Expose Openshift Route for Bookinfo (useful when you trying to deploy with external traffic)
      shell: "oc expose svc productpage -n {{bookinfo_namespace}}"

    - name: Wait until all pods are running on bookinfo
      openshift_raw:
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            name: "{{item}}"
            namespace: "{{ bookinfo_namespace }}"
      register: replicaResult
      until: (replicaResult.result.status.ready_replicas is defined and replicaResult.result.status.ready_replicas == 1) or
           (replicaResult.result.status.readyReplicas is defined and replicaResult.result.status.readyReplicas == 1)
      with_items:
        - productpage-v1
        - details-v1
        - ratings-v1
        - reviews-v1
        - reviews-v2
        - reviews-v3
      retries: "{{ hostvars['localhost']['check_retries'] }}"
      delay: 10

    - name: Wait until mongodb pods are running
      openshift_raw:
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            name: "{{item}}"
            namespace: "{{ bookinfo_namespace }}"
      register: replicaResult
      when: "mongodb is defined and mongodb == 'true'"
      until: (replicaResult.result.status.ready_replicas is defined and replicaResult.result.status.ready_replicas == 1) or
           (replicaResult.result.status.readyReplicas is defined and replicaResult.result.status.readyReplicas == 1)
      with_items:
        - ratings-v2-mongodb
        - mongodb-v1
      retries: "{{ hostvars['localhost']['check_retries'] }}"
      delay: 10

    - name: Wait until mysql pods are running
      openshift_raw:
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            name: "{{item}}"
            namespace: "{{ bookinfo_namespace }}"
      register: replicaResult
      when: "mysql is defined and mysql == 'true'"
      until: (replicaResult.result.status.ready_replicas is defined and replicaResult.result.status.ready_replicas == 1) or
           (replicaResult.result.status.readyReplicas is defined and replicaResult.result.status.readyReplicas == 1)
      with_items:
        - ratings-v2-mysql
        - mysqldb-v1
      retries: "{{ hostvars['localhost']['check_retries'] }}"
      delay: 10

    - name: Get Openshift Route
      shell: oc get route productpage -o jsonpath='{.spec.host}{"\n"}' -n {{bookinfo_namespace}}
      when: ingress_route is defined and ingress_route == 'false' and traffic_generator is defined and traffic_generator == 'true'
      register: openshift_route


    - name: Get Ingress Route
      shell: oc get route istio-ingressgateway -o jsonpath='{.spec.host}{"\n"}' -n istio-system
      when: ingress_route is defined and ingress_route == 'true' and traffic_generator is defined and traffic_generator == 'true'
      register: internal_route

    - name: Define duration of Traffic Generator
      set_fact:
        duration: 0
      when: duration is not defined

    - name: Deploy Kiali Traffic Generator Configmap to Openshift Route
      shell: "curl https://raw.githubusercontent.com/kiali/kiali-test-mesh/master/traffic-generator/openshift/traffic-generator-configmap.yaml | DURATION='0s' ROUTE='http://{{ openshift_route ['stdout'] }}/productpage' RATE='{{rate}}'  envsubst | oc apply -n {{bookinfo_namespace}} -f -"
      when: ingress_route is defined and ingress_route == 'false' and traffic_generator is defined and traffic_generator == 'true'

    - name: Deploy Kiali Traffic Generator Configmap to Ingress Route
      shell: "curl https://raw.githubusercontent.com/kiali/kiali-test-mesh/master/traffic-generator/openshift/traffic-generator-configmap.yaml | DURATION='0' ROUTE='http://{{ internal_route ['stdout'] }}/productpage' RATE='{{rate}}'  envsubst | oc apply -n {{bookinfo_namespace}} -f -"
      when: ingress_route is defined and ingress_route == 'true' and traffic_generator is defined and traffic_generator == 'true'

    - name: Deploy Kiali Traffic Generator
      shell: "curl https://raw.githubusercontent.com/kiali/kiali-test-mesh/master/traffic-generator/openshift/traffic-generator.yaml | oc apply -n {{bookinfo_namespace}} -f -"
      when: traffic_generator is defined and traffic_generator == 'true'
