
- name: Get Kiali Configmap
  set_fact:
      roles: '{{ lookup("k8s", api_version="rbac.authorization.k8s.io/v1", kind="Role", namespace="istio-system", resource_name="kiali-viewer") }}'

- name: Get Roles
  k8s_facts:
   api_version: rbac.authorization.k8s.io/v1
   kind: Role
   namespace: "{{ item[0] }}"
   name: "{{ item[1] }}"
  register: roles
  with_nested:
    - "{{ kiali.accessible_namespaces }}"
    - ['kiali', 'kiali-viewer']
 


- name: Multi-Tenancy - Assert that Namespaces have the correct Roles
  assert:
    that: "{{ item.resources | length == 1 }}"
  with_items:
  - "{{ roles.results }}"