# These are the actual variables used by the role. You will notice it is
# one big dictionary (key="kiali_vars") whose child dictionaries mimic those
# as defined in defaults/main.yml.
# The child dictionaries below will have values that are a combination of the default values
# (as found in defaults/main.yaml) and user-supplied values.
# Without this magic, a user supplying only one key/value pair in a child dictionary will
# clear out (make undefined) all the rest of the key/value pairs in that child dictionary.
# This is not what we want. We want the rest of the dictionary to keep the defaults,
# thus allowing the user to override only a subset of key/values in a dictionary.
#
# I found this trick at https://groups.google.com/forum/#!topic/Ansible-project/pGbRYZyqxZ4
# I tweeked that solution a little bit because I did not want to require the user to supply
# everything under a main "kiali_vars" dictionary.

kiali_vars:
  installation_tag: "{{ installation_tag | default(kiali_defaults.installation_tag) }}"
  istio_namespace: "{{ istio_namespace | default(kiali_defaults.istio_namespace) }}"

  api: |
    {%- if api is defined and api is iterable -%}
    {{ kiali_defaults.api | combine(api, recursive=True) }}
    {%- else -%}
    {{ kiali_defaults.api }}
    {%- endif -%}

  auth: |
    {%- if auth is defined and auth is iterable -%}
    {{ kiali_defaults.auth | combine(auth, recursive=True) }}
    {%- else -%}
    {{ kiali_defaults.auth }}
    {%- endif -%}

  deployment: |
    {%- if deployment is defined and deployment is iterable -%}
    {{ kiali_defaults.deployment | combine(deployment, recursive=True) }}
    {%- else -%}
    {{ kiali_defaults.deployment }}
    {%- endif -%}

  external_services: |
    {%- if external_services is defined and external_services is iterable -%}
    {{ kiali_defaults.external_services | combine(external_services, recursive=True) }}
    {%- else -%}
    {{ kiali_defaults.external_services }}
    {%- endif -%}

  identity: |
    {%- if identity is defined and identity is iterable -%}
    {{ kiali_defaults.identity | combine(identity, recursive=True) }}
    {%- else -%}
    {{ kiali_defaults.identity }}
    {%- endif -%}

  istio_labels: |
    {%- if istio_labels is defined and istio_labels is iterable -%}
    {{ kiali_defaults.istio_labels | combine(istio_labels, recursive=True) }}
    {%- else -%}
    {{ kiali_defaults.istio_labels }}
    {%- endif -%}

  kubernetes_config: |
    {%- if kubernetes_config is defined and kubernetes_config is iterable -%}
    {{ kiali_defaults.kubernetes_config | combine(kubernetes_config, recursive=True) }}
    {%- else -%}
    {{ kiali_defaults.kubernetes_config }}
    {%- endif -%}

  login_token: |
    {%- if login_token is defined and login_token is iterable -%}
    {{ kiali_defaults.login_token | combine(login_token, recursive=True) }}
    {%- else -%}
    {{ kiali_defaults.login_token }}
    {%- endif -%}

  server: |
    {%- if server is defined and server is iterable -%}
    {{ kiali_defaults.server | combine(server, recursive=True) }}
    {%- else -%}
    {{ kiali_defaults.server }}
    {%- endif -%}

