apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  auth:
    strategy: $AUTH_STRATEGY
  deployment:
    image_version: $KIALI_IMAGE_VERSION
    namespace: $NAMESPACE
    service_type: $SERVICE_TYPE
    verbose_mode: $VERBOSE_MODE
